modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="loydmod"
version="1.0.0"
displayName="Land Of Your Dreams"
credits="I created this using mod maker MCreator - https://mcreator.net/about"
displayURL="https://www.curseforge.com/minecraft/mc-mods/land-of-your-dreams"
logoFile="logo.png"
authors="OceanicOxen using MCreator"
description='''
This is a mod that allows the player to enter dream worlds 
'''

[[dependencies.loydmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




