modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="loydmod"
version="1.0.0"
displayName="Land Of Your Dreams"
credits="I created this using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="OceanicOxen using MCreator"
description='''
This is a mod that allows the player to enter dream worlds 
'''

[[dependencies.loydmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




